authenticate/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "authenticate"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='authenticate/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authenticate/logout.html'), name='logout'),
    path('register/', views.register_user, name='register'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='authenticate/change_password.html' , success_url=reverse_lazy('authenticate:password_change_done')), name='change_password'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='authenticate/password_change_done.html'),name='password_change_done'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html' , success_url=reverse_lazy('authenticate:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html' , success_url=reverse_lazy('authenticate:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

dependent/urls.py
from django.urls import include, path

from . import views
app_name = "dependent"

urlpatterns = [
     path('', views.index, name="home"),
     path('details/<int:id>', views.details, name="details"),
     path('update/<int:pk>/', views.person_update_view, name='person_change'),
     path('create', views.create, name="create"),
     path('ajax/load_division/', views.load_division, name='ajax_load_division'), # AJAX
     path('ajax/load-district/', views.load_district, name='ajax_load_district'), # AJAX
     path('ajax/load-subdistrict/', views.load_subdistrict, name='ajax_load_subdistrict'), # AJAX
]

myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dependent.urls", namespace="dependent")),
    path('', include("authenticate.urls", namespace="authenticate"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False

dependent/models.py
from django.db import models


class Country(models.Model):
	name = models.CharField(max_length=40)

	def __str__(self):
		return self.name

class Division(models.Model):
	country = models.ForeignKey(Country, on_delete=models.CASCADE)
	name = models.CharField(max_length=40)

	def __str__(self):
		return self.name

class District(models.Model):
	division = models.ForeignKey(Division, on_delete=models.CASCADE)
	name = models.CharField(max_length=40)

	def __str__(self):
		return self.name

class SubDistrict(models.Model):
	district = models.ForeignKey(District, on_delete=models.CASCADE)
	name = models.CharField(max_length=40)

	def __str__(self):
		return self.name

class Person(models.Model):
	name = models.CharField(max_length=40)
	father_name = models.CharField(max_length=40)
	mother_name = models.CharField(max_length=40)
	nid = models.CharField(max_length=40)
	religion = models.CharField(max_length=50)
	image = models.FileField(upload_to="person image" , blank=True)
	married_status = models.BooleanField(default=False)

	subdistrict = models.ForeignKey(SubDistrict, on_delete=models.CASCADE)
	district = models.ForeignKey(District, on_delete=models.CASCADE)
	division = models.ForeignKey(Division, on_delete=models.CASCADE)
	country = models.ForeignKey(Country, on_delete=models.CASCADE)
	def __str__(self):
		return self.name
    

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>Hello, world!</title>
  </head>
  <body>
  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container" >
      <a class="navbar-brand" href="/">Home</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dependent:create' %}">Create Person</a>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link"> **User : {{user.username}} **</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authenticate:change_password' %}">Change Password</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authenticate:logout' %}">Log Out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authenticate:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authenticate:login' %}">Login</a>
          </li>
        {% endif %}
        </ul>
      </div>
       </div>
    </nav>
   
    {% block content %}

    {% endblock content %}

    
  </body>
</html>

templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for dividion in dividions %}
<option value="{{ dividion.pk }}">{{ dividion.name }}</option>
{% endfor %}

templates/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container" >
      <div class="mx-auto" >
       <div class="text-center mt-5" >
            <h3 class="mb-5"> Create a Person </h3>
            <form method="post" id="personForm" enctype="multipart/form-data"  data-cities-url="{% url 'dependent:ajax_load_division' %}" data-district-url="{% url 'dependent:ajax_load_district' %}" data-subdistrict-url="{% url 'dependent:ajax_load_subdistrict' %}">
              {% csrf_token %}
              <div class="row" >
                <div class="col-md-3 col-lg-3" >
                    {{ form.name|as_crispy_field }}
                    {{ form.religion|as_crispy_field }}
                    {{ form.country|as_crispy_field }}         
                </div>
                <div class="col-md-3 col-lg-3" >             
                    {{ form.father_name|as_crispy_field }}             
                    {{ form.image|as_crispy_field }}           
                    {{ form.division|as_crispy_field }}          
                </div>
                <div class="col-md-3 col-lg-3" >              
                    {{ form.mother_name|as_crispy_field }}
                    {{ form.married_status|as_crispy_field }}
                    {{ form.district|as_crispy_field }} 
                </div>
                <div class="col-md-3 col-lg-3" >
                    {{ form.nid|as_crispy_field }}
                    <br>
                    <br><br><br>
                    {{ form.subdistrict|as_crispy_field }} 
                </div>
            </div>
            <input class="mt-4 mb-4 btn-primary btn-lg btncustom" type="submit" value="Submit">
            </form>

            
      </div>
      </div>
    </div>

<script src="{% static '3.3.1main.js' %}"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_division").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>
<script>
    $("#id_division").change(function () {
        const url = $("#personForm").attr("data-district-url");  // get the url of the `load_cities` view
        const divisionId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'division_id': divisionId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>

<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-subdistrict-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_subdistrict").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>

{% endblock content %}

templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container" >
      <div class="mx-auto mb-5" >
        <div class="card mb-3 mt-5">
        <div class="row mx-auto">
            {% if person.image %}
            <img class="card-img-top cus" src="{{person.image.url}}" height="300px" width="400px" alt="Card image cap">
            {% else %}
            <img class="card-img-top cus" src="{% static '1.png' %}" height="300px" width="400px" alt="Card image cap">
            {% endif %}
            <div class="card-body text-center">
                <h3 class="card-title"> Name : {{person.name}}</h3>
                <h5 class="card-text"> Father Name : <small class="text-muted">{{person.father_name}}</small></h5>
                <h5 class="card-text"> Mother Name : <small class="text-muted">{{person.mother_name}}</small></h5>
                <h5 class="card-text">  Religion : <small class="text-muted">{{person.religion}}</small></h5>
                <h5 class="card-text">  Married Status : <small class="text-muted">{{person.married_status}}</small></h5>
                <h5 class="card-text"><small class="text-muted">NID NO : {{person.nid}}</small></h5>
                <br>
                <a class="btn btn-primary" href="{% url 'dependent:person_change' pk=person.id %}">Edit</a>
            </div>
            <div class="card-body text-center">
                
                <h5 class="card-text"> Country : <small class="text-muted">{{person.country}}</small></h5>
                <h5 class="card-text">  Division : <small class="text-muted">{{person.division}}</small></h5>
                <h5 class="card-text">  District : <small class="text-muted">{{person.district}}</small></h5>
                <h5 class="card-text">  Sub-District : <small class="text-muted">{{person.subdistrict}}</small></h5>
            </div>
            
        </div>
        </div>
      </div>
    </div>



{% endblock content %}

templates/district_dropdown_list_options.html
<option value="">---------</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container" >
      <div class="mx-auto mb-5" >
        <div class="text-center mt-5" >
              <h3> Search The person info </h3>
              <form method="get" id="personForm" data-cities-url="{% url 'dependent:ajax_load_division' %}" data-district-url="{% url 'dependent:ajax_load_district' %}" data-subdistrict-url="{% url 'dependent:ajax_load_subdistrict' %}">
                <div class="row" >
                    <div class="col-md-3 col-lg-3" >
                        {{ form.country|as_crispy_field }}         
                    </div>
                    <div class="col-md-3 col-lg-3" >                  
                        {{ form.division|as_crispy_field }}          
                    </div>
                    <div class="col-md-3 col-lg-3" >              
                        {{ form.district|as_crispy_field }} 
                    </div>
                    <div class="col-md-3 col-lg-3" >
                        {{ form.subdistrict|as_crispy_field }} 
                    </div>
                </div>
                <input class="mt-4 mb-4 btn-primary btn-lg btncustom" type="submit" value="Submit">
              </form>
              <hr>
        </div>
        <div class="row">
          <div class="card-deck">

            {% for p in person %}
              <div class="col-lg-3">
                <div class="card mb-3">
                  {% if p.image %}
                  <img class="card-img-top" src="{{p.image.url}}" height="200px" alt="Card image cap">
                  {% else %}
                  <img class="card-img-top" src="{% static '1.png' %}" height="200px" alt="Card image cap">
                  {% endif %}
                  <div class="card-body">
                    <h6 class="card-title"> Name : {{p.name}}</h6>
                    {% comment %} <p>Father Name : {{p.father_name}}</p> {% endcomment %}
                    <a href="{% url 'dependent:details' id=p.id %}">Details</a>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted">NID No : {{p.nid}}</small> 
                  </div>
                </div>
              </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>


<script src="{% static '3.3.1main.js' %}"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_division").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>
<script>
    $("#id_division").change(function () {
        const url = $("#personForm").attr("data-district-url");  // get the url of the `load_cities` view
        const divisionId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'division_id': divisionId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>

<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-subdistrict-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_subdistrict").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>
{% endblock content %}

templates/subdistrict_dropdown_list_options.html
<option value="">---------</option>
{% for subdistrict in subdistricts %}
<option value="{{ subdistrict.pk }}">{{ subdistrict.name }}</option>
{% endfor %}